### ISSUE TITLE
Pending and description operators not working in Ruby 2.0+

### ISSUE THREAD

**Issue by ghost** [peterc/testrocket#6]
I'm writing up an article on TestRocket and wanted to know why the `~` and `!` unary operators for Procs do not work in Ruby 2.0+ (2.1.2 in my case)? I realise that Ruby 1.9 is only supported but was wondering whether you'd be able to point me to some Ruby Core issue thread where the removal of this feature was discussed.

``` bash
[7] pry(main)> ~-> { "this is a pending test" }
NoMethodError: undefined method `~' for #<Proc:0x007fb7d3aa8678@(pry):7 (lambda)>
from (pry):7:in `__pry__'
[8] pry(main)> !-> { "use this for descriptive output and to separate your test parts" }
=> false
```
